# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0dda47c974eec7620951a7f93fdde7f7fc4507921fcd01384387c568391686d2566eb509420bde6a074b6feb784dc97650499b5ef049528be4f820ea5e97c35

test:
  secret_key_base: 33b25db409919b1982fb8478d8ddab86008365e415859e4ef45eb8873405a8966c4bd85e387c9404df447e649e55eb0ae0f993359905196ac1c7ad4d29e58a6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
